In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime as dt

# Working on Ride Sharing CSV File

In [2]:
file_path_ride_sharing = '/content/drive/MyDrive/AI/Data Analysis/DA with Python/ride_sharing_new.csv'

In [3]:
ride_sharing = pd.read_csv(file_path_ride_sharing, delimiter=',')
ride_sharing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25760 entries, 0 to 25759
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       25760 non-null  int64
 1   duration         25760 non-null  object
 2   station_A_id     25760 non-null  int64
 3   station_A_name   25760 non-null  object
 4   station_B_id     25760 non-null  int64
 5   station_B_name   25760 non-null  object
 6   bike_id          25760 non-null  int64
 7   user_type        25760 non-null  int64
 8   user_birth_year  25760 non-null  int64
 9   user_gender      25760 non-null  object
dtypes: int64(6), object(4)
memory usage: 2.0+ MB

In [4]:
ride_sharing.describe()

         Unnamed: 0  station_A_id  ...     user_type  user_birth_year
count  25760.000000  25760.000000  ...  25760.000000     25760.000000
mean   12879.500000     31.023602  ...      2.008385      1983.054969
std     7436.415803     26.409263  ...      0.704541        10.010992
min        0.000000      3.000000  ...      1.000000      1901.000000
25%     6439.750000     15.000000  ...      2.000000      1978.000000
50%    12879.500000     21.000000  ...      2.000000      1985.000000
75%    19319.250000     67.000000  ...      3.000000      1990.000000
max    25759.000000     81.000000  ...      3.000000      2001.000000

[8 rows x 6 columns]

In [5]:
ride_sharing

       Unnamed: 0    duration  ...  user_birth_year user_gender
0               0  12 minutes  ...             1959        Male
1               1  24 minutes  ...             1965        Male
2               2   8 minutes  ...             1993        Male
3               3   4 minutes  ...             1979        Male
4               4  11 minutes  ...             1994        Male
...           ...         ...  ...              ...         ...
25755       25755  11 minutes  ...             2000        Male
25756       25756  10 minutes  ...             1998        Male
25757       25757  14 minutes  ...             1995        Male
25758       25758  14 minutes  ...             1995        Male
25759       25759  29 minutes  ...             1990        Male

[25760 rows x 10 columns]

## Converting Duration column into integer

In [6]:
ride_sharing['duration_trim'] = ride_sharing['duration'].str.strip('minutes')
ride_sharing['duration_trim']

0        12
1        24
2         8
3         4
4        11
        ...
25755    11
25756    10
25757    14
25758    14
25759    29
Name: duration_trim, Length: 25760, dtype: object

In [7]:
ride_sharing['duration_time'] = ride_sharing['duration_trim'].astype('int')
ride_sharing['duration_time']

0        12
1        24
2         8
3         4
4        11
         ..
25755    11
25756    10
25757    14
25758    14
25759    29
Name: duration_time, Length: 25760, dtype: int64

In [8]:
assert ride_sharing['duration_time'].dtype == int

In [9]:
ride_sharing[['duration', 'duration_trim', 'duration_time']]

         duration duration_trim  duration_time
0      12 minutes           12              12
1      24 minutes           24              24
2       8 minutes            8               8
3       4 minutes            4               4
4      11 minutes           11              11
...           ...           ...            ...
25755  11 minutes           11              11
25756  10 minutes           10              10
25757  14 minutes           14              14
25758  14 minutes           14              14
25759  29 minutes           29              29

[25760 rows x 3 columns]

In [10]:
ride_sharing['duration_time'].mean()

11.389052795031056

## Converting Usertype column into Category

In [11]:
ride_sharing['user_type']

0        2
1        2
2        3
3        1
4        2
        ..
25755    1
25756    2
25757    2
25758    2
25759    3
Name: user_type, Length: 25760, dtype: int64

In [12]:
ride_sharing['user_type'].unique()

array([2, 3, 1])

In [13]:
ride_sharing['user_type'] = ride_sharing['user_type'].astype(int)
ride_sharing.loc[ride_sharing['user_type'] > 3, 'user_type'] = 0
ride_sharing['user_type'].unique()

array([2, 3, 1])

In [14]:
ride_sharing['user_type'].dtype

dtype('int64')

In [15]:
ride_sharing['user_type'] = ride_sharing['user_type'].astype('category')
ride_sharing['user_type'].dtype

CategoricalDtype(categories=[1, 2, 3], ordered=False)

## Converting birth_year column into date time

In [16]:
ride_sharing['user_birth_year'].dtype

dtype('int64')

In [17]:
ride_sharing['user_birth_year'] = pd.to_datetime(ride_sharing['user_birth_year'])
ride_sharing['user_birth_year'].dtype

dtype('<M8[ns]')

In [18]:
# Get today date
today_date = dt.date.today()
today_date

# Get Max time of the day
max_time = dt.datetime.max.time()
max_time

# Combine both
combine_date_time = dt.datetime.combine(today_date, max_time)
print(combine_date_time)

ride_sharing.loc[ride_sharing['user_birth_year'] > combine_date_time, 'user_birth_year'] = today_date
print(ride_sharing['user_birth_year'].max())

2021-09-29 23:59:59.999999
1970-01-01 00:00:00.000002001

## Finding Duplicates

In [19]:
duplicates = ride_sharing.duplicated(subset='bike_id', keep=False)
duplicates.unique(), duplicates.value_counts()

(array([ True, False]), True     25717
 False       43
 dtype: int64)

In [20]:
duplicates

0        True
1        True
2        True
3        True
4        True
         ...
25755    True
25756    True
25757    True
25758    True
25759    True
Length: 25760, dtype: bool

In [21]:
duplicated_rides = ride_sharing[duplicates].sort_values('bike_id')
duplicated_rides

       Unnamed: 0    duration  ...  duration_trim duration_time
3638         3638  12 minutes  ...            12             12
6088         6088   5 minutes  ...             5              5
10857       10857   4 minutes  ...             4              4
10045       10045  13 minutes  ...            13             13
16104       16104  10 minutes  ...            10             10
...           ...         ...  ...            ...           ...
8812         8812  10 minutes  ...            10             10
6815         6815   5 minutes  ...             5              5
8456         8456   7 minutes  ...             7              7
8300         8300   6 minutes  ...             6              6
8380         8380   8 minutes  ...             8              8

[25717 rows x 12 columns]

In [22]:
duplicated_rides[['bike_id', 'duration', 'user_birth_year']]

       bike_id    duration                user_birth_year
3638        11  12 minutes  1970-01-01 00:00:00.000001988
6088        11   5 minutes  1970-01-01 00:00:00.000001985
10857       11   4 minutes  1970-01-01 00:00:00.000001987
10045       27  13 minutes  1970-01-01 00:00:00.000001989
16104       27  10 minutes  1970-01-01 00:00:00.000001970
...        ...         ...                            ...
8812      6638  10 minutes  1970-01-01 00:00:00.000001986
6815      6638   5 minutes  1970-01-01 00:00:00.000001995
8456      6638   7 minutes  1970-01-01 00:00:00.000001983
8300      6638   6 minutes  1970-01-01 00:00:00.000001962
8380      6638   8 minutes  1970-01-01 00:00:00.000001984

[25717 rows x 3 columns]

## Dropping Complet Duplicated from Ride Sharing

In [23]:
ride_drop_duplicate = ride_sharing.drop_duplicates()
ride_drop_duplicate

       Unnamed: 0    duration  ...  duration_trim duration_time
0               0  12 minutes  ...            12             12
1               1  24 minutes  ...            24             24
2               2   8 minutes  ...             8              8
3               3   4 minutes  ...             4              4
4               4  11 minutes  ...            11             11
...           ...         ...  ...            ...           ...
25755       25755  11 minutes  ...            11             11
25756       25756  10 minutes  ...            10             10
25757       25757  14 minutes  ...            14             14
25758       25758  14 minutes  ...            14             14
25759       25759  29 minutes  ...            29             29

[25760 rows x 12 columns]

In [24]:
ride_drop_duplicate[['bike_id', 'duration', 'user_birth_year']].sort_values('bike_id')

       bike_id    duration                user_birth_year
10857       11   4 minutes  1970-01-01 00:00:00.000001987
6088        11   5 minutes  1970-01-01 00:00:00.000001985
3638        11  12 minutes  1970-01-01 00:00:00.000001988
3431        27  10 minutes  1970-01-01 00:00:00.000001988
2747        27   6 minutes  1970-01-01 00:00:00.000001992
...        ...         ...                            ...
8456      6638   7 minutes  1970-01-01 00:00:00.000001983
8812      6638  10 minutes  1970-01-01 00:00:00.000001986
6815      6638   5 minutes  1970-01-01 00:00:00.000001995
8380      6638   8 minutes  1970-01-01 00:00:00.000001984
8300      6638   6 minutes  1970-01-01 00:00:00.000001962

[25760 rows x 3 columns]

In [25]:
ride_uniq = ride_drop_duplicate.groupby('bike_id')
print(ride_uniq)
ride_uniq.describe()

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x7f9ee775d650>

        Unnamed: 0                             ... duration_time
             count          mean          std  ...           50%    75%    max
bike_id                                        ...
11             3.0   6861.000000  3671.053936  ...           5.0   8.50   12.0
27            18.0  13404.722222  7910.772364  ...          11.0  15.25   25.0
37            12.0  10026.583333  5629.998990  ...           6.5   8.00   13.0
38             9.0  14801.555556  7790.238830  ...           9.0  10.00   17.0
43             7.0   9310.714286  7251.762124  ...          12.0  15.00   16.0
...            ...           ...          ...  ...           ...    ...    ...
6147          18.0  17980.055556  5176.177780  ...           9.5  11.75   18.0
6234          19.0  12927.631579  8611.706440  ...           8.0  13.00  142.0
6235          40.0  12172.250000  7277.186579  ...           9.0  10.25   18.0
6315           1.0  20831.000000          NaN  ...           7.0   7.00    7.0
6638           5.0   8152.600000   772.895724  ...           7.0   8.00   10.0

[1805 rows x 32 columns]

# Working on Airlines_final CSV File

In [26]:
file_path_airline = '/content/drive/MyDrive/AI/Data Analysis/DA with Python/airlines_final.csv'

In [27]:
airlines = pd.read_csv(file_path_airline)
airlines

      Unnamed: 0    id  ...         safety        satisfaction
0              0  1351  ...        Neutral      Very satisfied
1              1   373  ...      Very safe      Very satisfied
2              2  2820  ...  Somewhat safe             Neutral
3              3  1157  ...      Very safe  Somewhat satsified
4              4  2992  ...      Very safe  Somewhat satsified
...          ...   ...  ...            ...                 ...
2472        2804  1475  ...        Neutral  Somewhat satsified
2473        2805  2222  ...      Very safe      Very satisfied
2474        2806  2684  ...      Very safe      Very satisfied
2475        2807  2549  ...  Somewhat safe      Very satisfied
2476        2808  2162  ...      Very safe  Somewhat satsified

[2477 rows x 13 columns]

In [28]:
airlines.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2477 entries, 0 to 2476
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     2477 non-null   int64
 1   id             2477 non-null   int64
 2   day            2477 non-null   object
 3   airline        2477 non-null   object
 4   destination    2477 non-null   object
 5   dest_region    2477 non-null   object
 6   dest_size      2477 non-null   object
 7   boarding_area  2477 non-null   object
 8   dept_time      2477 non-null   object
 9   wait_min       2477 non-null   float64
 10  cleanliness    2477 non-null   object
 11  safety         2477 non-null   object
 12  satisfaction   2477 non-null   object
dtypes: float64(1), int64(2), object(10)
memory usage: 251.7+ KB

In [29]:
airlines.columns

Index(['Unnamed: 0', 'id', 'day', 'airline', 'destination', 'dest_region',
       'dest_size', 'boarding_area', 'dept_time', 'wait_min', 'cleanliness',
       'safety', 'satisfaction'],
      dtype='object')

### Print Uniq values of Survey columns

In [31]:
print("Cleanliness: ", airlines['cleanliness'].unique())
print("Safety: ", airlines['safety'].unique())
print("Satisfaction: ", airlines['satisfaction'].unique())

Cleanliness:  ['Clean' 'Average' 'Somewhat clean' 'Somewhat dirty' 'Dirty']
Safety:  ['Neutral' 'Very safe' 'Somewhat safe' 'Very unsafe' 'Somewhat unsafe']
Satisfaction:  ['Very satisfied' 'Neutral' 'Somewhat satsified' 'Somewhat unsatisfied'
 'Very unsatisfied']

# Print Uniq values of Destination region and size

In [33]:
print("Desination Region: ", airlines['dest_region'].unique())
print("Destination Size: ", airlines['dest_size'].unique())

Desination Region:  ['Asia' 'Canada/Mexico' 'West US' 'East US' 'Midwest US' 'EAST US'
 'Middle East' 'Europe' 'eur' 'Central/South America'
 'Australia/New Zealand' 'middle east']
Destination Size:  ['Hub' 'Small' '    Hub' 'Medium' 'Large' 'Hub     ' '    Small'
 'Medium     ' '    Medium' 'Small     ' '    Large' 'Large     ']

### Converting Wait Stay time to Short, Medium, Long

In [34]:
label_ranges = [0, 60, 180, np.inf]
label_names = ['short', 'medium', 'long']

airlines['wait_type'] = pd.cut(airlines['wait_min'],
                               bins=label_ranges,
                               labels=label_names)
airlines['wait_type']

0       medium
1       medium
2       medium
3         long
4         long
         ...
2472      long
2473    medium
2474    medium
2475    medium
2476      long
Name: wait_type, Length: 2477, dtype: category
Categories (3, object): ['short' < 'medium' < 'long']

### Converting Days into Weekday or Weekend

In [35]:
airlines['day'].unique()

array(['Tuesday', 'Friday', 'Thursday', 'Wednesday', 'Saturday', 'Sunday',
       'Monday'], dtype=object)

In [38]:
days_mapping = {'Monday':'weekday', 'Tuesday':'weekday', 'Wednesday':'weekday', 'Thursday':'weekday',
                'Friday':'weekday', 'Saturday':'weekend', 'Sunday':'weekend'}

airlines['day_week'] = airlines['day'].replace(days_mapping)
airlines['day_week']

0       weekday
1       weekday
2       weekday
3       weekday
4       weekday
         ...
2472    weekday
2473    weekday
2474    weekday
2475    weekday
2476    weekend
Name: day_week, Length: 2477, dtype: object

In [39]:
airlines['day_week'].unique()

array(['weekday', 'weekend'], dtype=object)

In [40]:
airlines['day_week'].value_counts()

weekday    2000
weekend     477
Name: day_week, dtype: int64

In [41]:
assert airlines['day_week'].str.contains('Ms.|Mr.|Miss|Dr.').any() == False

In [42]:
airlines

      Unnamed: 0    id        day  ...        satisfaction wait_type day_week
0              0  1351    Tuesday  ...      Very satisfied    medium  weekday
1              1   373     Friday  ...      Very satisfied    medium  weekday
2              2  2820   Thursday  ...             Neutral    medium  weekday
3              3  1157    Tuesday  ...  Somewhat satsified      long  weekday
4              4  2992  Wednesday  ...  Somewhat satsified      long  weekday
...          ...   ...        ...  ...                 ...       ...      ...
2472        2804  1475    Tuesday  ...  Somewhat satsified      long  weekday
2473        2805  2222   Thursday  ...      Very satisfied    medium  weekday
2474        2806  2684     Friday  ...      Very satisfied    medium  weekday
2475        2807  2549    Tuesday  ...      Very satisfied    medium  weekday
2476        2808  2162   Saturday  ...  Somewhat satsified      long  weekend

[2477 rows x 15 columns]